{
 "title": "Slow Queries in Real-Time",
 "tags": [ "MySQL" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mysql_processlist_alert_metric_VALUE,service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Slow Queries Present: ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_processlist_alert_metric_VALUE{service_name=\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Slow Queries: ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mysql_processlist_alert_metric_TOTAL_ROWS{service_name=\"$service_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Queries By User: ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (USER) (\r\n  mysql_processlist_status_custom_metric_TIME{service_name=\"$service_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Query Details: ",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by (ID, USER, HOST, DB, STATE, INFO) (mysql_processlist_status_custom_metric_TIME {service_name=\"$service_name\"})",
     "legendFormat": "auto"
    }
   ]
  }
 ]
}