{
 "title": "Test Query",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Slow Queries Present: ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_processlist_alert_metric_VALUE",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Slow Queries: ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mysql_processlist_alert_metric_TOTAL_ROWS",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Query Details: ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (ID, USER, HOST, DB, STATE, INFO) (mysql_processlist_status_custom_metric_TIME)",
     "legendFormat": "auto"
    }
   ]
  }
 ]
}